# Generated by Django 3.0.2 on 2020-01-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='courses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peoples', to='polls.Course'),
        ),
    ]
